# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="${loader_version_range}"
license='${mod_license}'

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Thanks to thedarkcolour and all the contributors for making Kotlin for Forge"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.6,6.1.0)"
    ordering="NONE"
    side="BOTH"